apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-files
  labels:
    {{ include "default.labels" . | indent 4}}
  annotations:
    deploymentTime: {{ now | date "02.01.2006 15:04:05" }}
data:
{{ if not .Values.projectApp.settings.loggingConsoleDisabled }}
  FILEBEAT_YML: |-
{{ tpl ( .Files.Get "files/filebeat_console.yaml" ) . | indent 4 }}
{{ end }}

{{ if not .Values.projectApp.settings.logbackTcpInputLoggingDisabled }}
{{ .Chart.Name }}_CORE_LOGBACK_XML: |-
{{ tpl ( .Files.Get "files/logback.yaml" ) . | indent 4 }}
{{ end }}