apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{ include "default.labels" . | indent 4 }} 
  annotations:
    deploymentTime: {{ now | date "02.01.2006 15:04:05" }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http-{{ .Chart.Name }}
      port: {{ .Values.projectApp.env.ServerPort | default 8080 }} 
      protocol: TCP
      targetPort: {{ .Values.projectApp.env.ServerPort | default 8080 }}