apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cfg
  labels:
    {{ include "default.labels" . | indent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Chart.Name }}
data:
  SERVICE_NAME: "{{ .Chart.Name }}"
  SERVICE_VERSION: "v1.18"
  nginx.conf: |-
{{tpl (.Files.Get "files/nginx.conf") . | indent 4 }}
  project.conf: |-
{{tpl (.Files.Get "files/project.conf") . | indent 4 }}
  headers.txt: |-
{{tpl (.Files.Get "files/headers.txt") . | indent 4 }}
  project-ssl.conf: |-
{{tpl (.Files.Get "files/project-ssl.conf") . | indent 4 }}
  status.conf: |-
{{tpl (.Files.Get "files/status.conf") . | indent 4 }}
{{ if not .Values.projectIngressProxy.settings.elk.disabled }}
  filebeat.yml: |-
{{tpl (.Files.Get "files/filebeat.yml") . | indent 4 }}
{{ end }}
