apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{ include "default.labels" . | indent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Chart.Name }}
spec:
  ports:
  - name: http-{{ .Chart.Name }}
    protocol: TCP
    port: 443
    targetPort: 8443
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
  sessionAffinity: None
