{{ if not .Values.projectEgressProxy.settings.istioDisabled }}
apiVersion: networking.istio.io/v1alpha3  # Specifies the API version for Istio resources
kind: DestinationRule  # Defines the kind of resource, in this case, a DestinationRule for Istio
metadata:  # Metadata for the Istio resource
  name: {{.Chart.Name }}-vault-destination  # The name of the DestinationRule resource, based on the chart name
  namespace: {{ .Values.projectEgressProxy.vault.namespace }}  # The namespace where the DestinationRule will be created, from the Vault settings
  annotations:  # Annotations to store additional metadata
    deploymentTime: {{ now | date "02.01.2006 15:04:05" }}  # Adds the deployment time to the annotations
spec:  # The specification of the DestinationRule
  host: {{ .Values.projectEgressProxy.vault.domain }}  # Specifies the hostname of the Vault server for traffic routing
  trafficPolicy:  # Defines the traffic policy for the destination
    tls:  # TLS settings for secure communication
      mode: DISABLE  # Disables mTLS for communication with the Vault server
{{ end }}